# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-07-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_tweet_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='isReply',
            field=models.BooleanField(default=False, verbose_name='Is a reply?'),
        ),
    ]
