# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-07-07 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='hTag',
            new_name='hashTag',
        ),
    ]
