# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-06-16 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20190616_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='urlShortCode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
