# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-06-16 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_auto_20190616_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
