# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-07-01 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_shorturl_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='inputUrl',
            field=models.CharField(max_length=220, validators=[shortner.validators.validate_anup, shortner.validators.validate_inputUrl]),
        ),
    ]
