# Generated by Django 2.2.2 on 2019-06-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeTitle', models.TextField()),
                ('noticeType', models.TextField()),
                ('noticeBody', models.TextField()),
            ],
        ),
    ]
