# Generated by Django 2.2.2 on 2019-06-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notices',
            new_name='noticeData',
        ),
    ]
