# Generated by Django 2.2.2 on 2019-06-13 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_auto_20190613_0854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='noticeData',
            new_name='notice',
        ),
    ]
