# Generated by Django 2.2.2 on 2019-06-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0003_auto_20190613_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='noticeSlug',
            field=models.SlugField(null=True),
        ),
    ]
