# Generated by Django 2.2.2 on 2019-06-15 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0006_notice_noticeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='publishDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
