# Generated by Django 2.2.2 on 2019-06-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0007_auto_20190615_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-publishDate', '-updateDate', '-timestamp']},
        ),
    ]
