# Generated by Django 2.2.2 on 2019-06-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0008_auto_20190615_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='noticeImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
